/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.pds.smartstone.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the PersistedAttribute service. Represents a row in the &quot;Attribute&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.pds.smartstone.model.impl.PersistedAttributeModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.pds.smartstone.model.impl.PersistedAttributeImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PersistedAttribute
 * @generated
 */
@ProviderType
public interface PersistedAttributeModel extends BaseModel<PersistedAttribute> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a persisted attribute model instance should use the {@link PersistedAttribute} interface instead.
	 */

	/**
	 * Returns the primary key of this persisted attribute.
	 *
	 * @return the primary key of this persisted attribute
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this persisted attribute.
	 *
	 * @param primaryKey the primary key of this persisted attribute
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this persisted attribute.
	 *
	 * @return the uuid of this persisted attribute
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this persisted attribute.
	 *
	 * @param uuid the uuid of this persisted attribute
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the ID of this persisted attribute.
	 *
	 * @return the ID of this persisted attribute
	 */
	public long getId();

	/**
	 * Sets the ID of this persisted attribute.
	 *
	 * @param id the ID of this persisted attribute
	 */
	public void setId(long id);

	/**
	 * Returns the type ID of this persisted attribute.
	 *
	 * @return the type ID of this persisted attribute
	 */
	public long getTypeId();

	/**
	 * Sets the type ID of this persisted attribute.
	 *
	 * @param typeId the type ID of this persisted attribute
	 */
	public void setTypeId(long typeId);

	/**
	 * Returns the value of this persisted attribute.
	 *
	 * @return the value of this persisted attribute
	 */
	@AutoEscape
	public String getValue();

	/**
	 * Sets the value of this persisted attribute.
	 *
	 * @param value the value of this persisted attribute
	 */
	public void setValue(String value);

	/**
	 * Returns the description of this persisted attribute.
	 *
	 * @return the description of this persisted attribute
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this persisted attribute.
	 *
	 * @param description the description of this persisted attribute
	 */
	public void setDescription(String description);

	/**
	 * Returns the language ID of this persisted attribute.
	 *
	 * @return the language ID of this persisted attribute
	 */
	public long getLanguageId();

	/**
	 * Sets the language ID of this persisted attribute.
	 *
	 * @param languageId the language ID of this persisted attribute
	 */
	public void setLanguageId(long languageId);

	/**
	 * Returns the created on of this persisted attribute.
	 *
	 * @return the created on of this persisted attribute
	 */
	public Date getCreatedOn();

	/**
	 * Sets the created on of this persisted attribute.
	 *
	 * @param createdOn the created on of this persisted attribute
	 */
	public void setCreatedOn(Date createdOn);

	/**
	 * Returns the created by of this persisted attribute.
	 *
	 * @return the created by of this persisted attribute
	 */
	public long getCreatedBy();

	/**
	 * Sets the created by of this persisted attribute.
	 *
	 * @param createdBy the created by of this persisted attribute
	 */
	public void setCreatedBy(long createdBy);

	/**
	 * Returns the modified on of this persisted attribute.
	 *
	 * @return the modified on of this persisted attribute
	 */
	public Date getModifiedOn();

	/**
	 * Sets the modified on of this persisted attribute.
	 *
	 * @param modifiedOn the modified on of this persisted attribute
	 */
	public void setModifiedOn(Date modifiedOn);

	/**
	 * Returns the modified by of this persisted attribute.
	 *
	 * @return the modified by of this persisted attribute
	 */
	public long getModifiedBy();

	/**
	 * Sets the modified by of this persisted attribute.
	 *
	 * @param modifiedBy the modified by of this persisted attribute
	 */
	public void setModifiedBy(long modifiedBy);

	/**
	 * Returns the deleted on of this persisted attribute.
	 *
	 * @return the deleted on of this persisted attribute
	 */
	public Date getDeletedOn();

	/**
	 * Sets the deleted on of this persisted attribute.
	 *
	 * @param deletedOn the deleted on of this persisted attribute
	 */
	public void setDeletedOn(Date deletedOn);

	/**
	 * Returns the deleted by of this persisted attribute.
	 *
	 * @return the deleted by of this persisted attribute
	 */
	public long getDeletedBy();

	/**
	 * Sets the deleted by of this persisted attribute.
	 *
	 * @param deletedBy the deleted by of this persisted attribute
	 */
	public void setDeletedBy(long deletedBy);

}