/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.pds.smartstone.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import com.pds.smartstone.model.PersistedAttributeType;
import com.pds.smartstone.model.PersistedAttributeTypeModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the PersistedAttributeType service. Represents a row in the &quot;AttributeType&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>PersistedAttributeTypeModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PersistedAttributeTypeImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PersistedAttributeTypeImpl
 * @generated
 */
public class PersistedAttributeTypeModelImpl
	extends BaseModelImpl<PersistedAttributeType>
	implements PersistedAttributeTypeModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a persisted attribute type model instance should use the <code>PersistedAttributeType</code> interface instead.
	 */
	public static final String TABLE_NAME = "AttributeType";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"id", Types.BIGINT}, {"name", Types.VARCHAR},
		{"code", Types.VARCHAR}, {"description", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("id", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("code", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table AttributeType (uuid_ VARCHAR(75) null,id LONG not null primary key,name VARCHAR(75) null,code VARCHAR(75) null,description VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table AttributeType";

	public static final String ORDER_BY_JPQL =
		" ORDER BY persistedAttributeType.code ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY AttributeType.code ASC";

	public static final String DATA_SOURCE = "extDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long CODE_COLUMN_BITMASK = 1L;

	public static final long ID_COLUMN_BITMASK = 2L;

	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public PersistedAttributeTypeModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return PersistedAttributeType.class;
	}

	@Override
	public String getModelClassName() {
		return PersistedAttributeType.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<PersistedAttributeType, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<PersistedAttributeType, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PersistedAttributeType, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((PersistedAttributeType)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<PersistedAttributeType, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<PersistedAttributeType, Object>
				attributeSetterBiConsumer = attributeSetterBiConsumers.get(
					attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(PersistedAttributeType)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<PersistedAttributeType, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<PersistedAttributeType, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, PersistedAttributeType>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			PersistedAttributeType.class.getClassLoader(),
			PersistedAttributeType.class, ModelWrapper.class);

		try {
			Constructor<PersistedAttributeType> constructor =
				(Constructor<PersistedAttributeType>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<PersistedAttributeType, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<PersistedAttributeType, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<PersistedAttributeType, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<PersistedAttributeType, Object>>();
		Map<String, BiConsumer<PersistedAttributeType, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap
					<String, BiConsumer<PersistedAttributeType, ?>>();

		attributeGetterFunctions.put("uuid", PersistedAttributeType::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<PersistedAttributeType, String>)
				PersistedAttributeType::setUuid);
		attributeGetterFunctions.put("id", PersistedAttributeType::getId);
		attributeSetterBiConsumers.put(
			"id",
			(BiConsumer<PersistedAttributeType, Long>)
				PersistedAttributeType::setId);
		attributeGetterFunctions.put("name", PersistedAttributeType::getName);
		attributeSetterBiConsumers.put(
			"name",
			(BiConsumer<PersistedAttributeType, String>)
				PersistedAttributeType::setName);
		attributeGetterFunctions.put("code", PersistedAttributeType::getCode);
		attributeSetterBiConsumers.put(
			"code",
			(BiConsumer<PersistedAttributeType, String>)
				PersistedAttributeType::setCode);
		attributeGetterFunctions.put(
			"description", PersistedAttributeType::getDescription);
		attributeSetterBiConsumers.put(
			"description",
			(BiConsumer<PersistedAttributeType, String>)
				PersistedAttributeType::setDescription);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_columnBitmask |= ID_COLUMN_BITMASK;

		if (!_setOriginalId) {
			_setOriginalId = true;

			_originalId = _id;
		}

		_id = id;
	}

	public long getOriginalId() {
		return _originalId;
	}

	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_name = name;
	}

	@Override
	public String getCode() {
		if (_code == null) {
			return "";
		}
		else {
			return _code;
		}
	}

	@Override
	public void setCode(String code) {
		_columnBitmask = -1L;

		if (_originalCode == null) {
			_originalCode = _code;
		}

		_code = code;
	}

	public String getOriginalCode() {
		return GetterUtil.getString(_originalCode);
	}

	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, PersistedAttributeType.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public PersistedAttributeType toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, PersistedAttributeType>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PersistedAttributeTypeImpl persistedAttributeTypeImpl =
			new PersistedAttributeTypeImpl();

		persistedAttributeTypeImpl.setUuid(getUuid());
		persistedAttributeTypeImpl.setId(getId());
		persistedAttributeTypeImpl.setName(getName());
		persistedAttributeTypeImpl.setCode(getCode());
		persistedAttributeTypeImpl.setDescription(getDescription());

		persistedAttributeTypeImpl.resetOriginalValues();

		return persistedAttributeTypeImpl;
	}

	@Override
	public int compareTo(PersistedAttributeType persistedAttributeType) {
		int value = 0;

		value = getCode().compareTo(persistedAttributeType.getCode());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof PersistedAttributeType)) {
			return false;
		}

		PersistedAttributeType persistedAttributeType =
			(PersistedAttributeType)object;

		long primaryKey = persistedAttributeType.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		PersistedAttributeTypeModelImpl persistedAttributeTypeModelImpl = this;

		persistedAttributeTypeModelImpl._originalUuid =
			persistedAttributeTypeModelImpl._uuid;

		persistedAttributeTypeModelImpl._originalId =
			persistedAttributeTypeModelImpl._id;

		persistedAttributeTypeModelImpl._setOriginalId = false;

		persistedAttributeTypeModelImpl._originalCode =
			persistedAttributeTypeModelImpl._code;

		persistedAttributeTypeModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<PersistedAttributeType> toCacheModel() {
		PersistedAttributeTypeCacheModel persistedAttributeTypeCacheModel =
			new PersistedAttributeTypeCacheModel();

		persistedAttributeTypeCacheModel.uuid = getUuid();

		String uuid = persistedAttributeTypeCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			persistedAttributeTypeCacheModel.uuid = null;
		}

		persistedAttributeTypeCacheModel.id = getId();

		persistedAttributeTypeCacheModel.name = getName();

		String name = persistedAttributeTypeCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			persistedAttributeTypeCacheModel.name = null;
		}

		persistedAttributeTypeCacheModel.code = getCode();

		String code = persistedAttributeTypeCacheModel.code;

		if ((code != null) && (code.length() == 0)) {
			persistedAttributeTypeCacheModel.code = null;
		}

		persistedAttributeTypeCacheModel.description = getDescription();

		String description = persistedAttributeTypeCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			persistedAttributeTypeCacheModel.description = null;
		}

		return persistedAttributeTypeCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<PersistedAttributeType, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<PersistedAttributeType, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PersistedAttributeType, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(
				attributeGetterFunction.apply((PersistedAttributeType)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<PersistedAttributeType, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<PersistedAttributeType, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PersistedAttributeType, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(
				attributeGetterFunction.apply((PersistedAttributeType)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, PersistedAttributeType>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private String _originalUuid;
	private long _id;
	private long _originalId;
	private boolean _setOriginalId;
	private String _name;
	private String _code;
	private String _originalCode;
	private String _description;
	private long _columnBitmask;
	private PersistedAttributeType _escapedModel;

}